/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ProgFlash.H
**     Project   : demo_serial_bootloader
**     Processor : 56F8323
**     Component : IntFLASH
**     Version   : Component 02.362, Driver 02.07, CPU db: 2.87.081
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 27/11/2020, 18:24
**     Abstract  :
**         This bean "IntFLASH" implements an access to internal FLASH.
**         The bean support reading/writing data into FLASH, erasing of
**         selected sector.
**         The bean supports events if the write interrupt is supported.
**         The bean supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The bean requires on-chip FLASH memory (not used/allocated by
**         other beans).
**     Settings  :
**         FLASH memory type                 : Program and Boot FLASH
**         Total Program FLASH memory size   : 16384 words
**         Program FLASH memory sector size  : 512 words
**         Total Boot FLASH memory size      : 4096 words
**         Boot FLASH memory sector size     : 256 words
**         Interrupt service                 : Disabled
**         Write method                      : Write
**         Wait in RAM                       : no
**     Contents  :
**         Busy                - bool ProgFlash_Busy(byte Block);
**         EraseFlash          - byte ProgFlash_EraseFlash(byte Block);
**         SetGlobalProtection - byte ProgFlash_SetGlobalProtection(bool ProtectAll);
**         GetByteFlash        - byte ProgFlash_GetByteFlash(ProgFlash_TAddress Addr, byte *Data);
**         SetBlockFlash       - byte ProgFlash_SetBlockFlash(ProgFlash_TDataAddress Source,...
**         DataPtr2Addr        - ProgFlash_TAddress ProgFlash_DataPtr2Addr(void* Addr);
**         FuncPtr2Addr        - ProgFlash_TAddress ProgFlash_FuncPtr2Addr(void(*Addr)());
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __ProgFlash
#define __ProgFlash

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

/* Include inherited beans */
#include "Cpu.h"

/* MODULE ProgFlash. */

/* Identifier of the program flash register bank */
#define PROG_REG_BANK 2

/* FLASH memory size and location in 16-bit words */
#define PROG_FLASH_START 0
#define PROG_FLASH_END   16383
#define PROG_FLASH_SECTOR_SIZE 512u
#define BOOT_FLASH_START 131072
#define BOOT_FLASH_END   135167
#define BOOT_FLASH_SECTOR_SIZE 256u

/* Flash memory blocks: */
#define PROG_FLASH_BLOCK_SIZE 16384
#define BOOT_FLASH_BLOCK_SIZE 4096
#define PROG_FLASH_BLOCK 0
#define BOOT_FLASH_BLOCK 1
#define PROG_BOOT_FLASH_MAX_BLOCK_NUM 1

/* Common data fields for all IntFLASH bean's modules */
#ifndef CommonFlashData
#define CommonFlashData

/* Flash user mode commands */
#define ERASE_VERIFY 0x05
#define PROGRAM      0x20
#define PAGE_ERASE   0x40
#define MASS_ERASE   0x41

/* FLASH memory configuration fields locations */
#define FM_PROG_MEM_TOP 0x3fff
#define BOOT_PROT_LOC 6
#define PRGM_PROT_LOC 5
#define DATA_PROT_LOC 4

#endif /* Common data fields for all IntFLASH bean's modules */

/* Old symbols */
#define ProgFlash_NumOfBlocks 1
#define ProgFlashStart PROG_FLASH_START
#define ProgFlashEnd   PROG_FLASH_END
#define BootFlashStart BOOT_FLASH_START
#define BootFlashEnd   BOOT_FLASH_END
#ifndef __BWUserType_ProgFlash_TAddress
#define __BWUserType_ProgFlash_TAddress
   typedef dword ProgFlash_TAddress;   /* Bean type for address to the FLASH.*/
#endif
#ifndef __BWUserType_ProgFlash_TDataAddress
#define __BWUserType_ProgFlash_TDataAddress
  typedef dword ProgFlash_TDataAddress; /* Bean type for data address. */
#endif


/*
Test the Command complete flag in the both register banks and
leave the original bank (the register bank is not changed after
the macro's execution is completed).
*/
#define ProgFlash_Busy(Block) ((bool)( \
  (getRegBit(FMUSTAT,CCIF)) ? \
    (changeRegBits(FMCR, 3), \
    ((getRegBit(FMUSTAT,CCIF)) ? \
      (changeRegBits(FMCR, 3), \
      FALSE) \
    : (changeRegBits(FMCR, 3), \
    TRUE))) \
  : (TRUE)))
/*
** ===================================================================
**     Method      :  ProgFlash_Busy (component IntFLASH)
**
**     Description :
**         Method return status of the FLASH device
**     Parameters  :
**         NAME            - DESCRIPTION
**         Block           - Block number. Not used for Freescale
**                           56800 and HCS12X derivates - any value may be passed.
**     Returns     :
**         ---             - TRUE/FALSE - FLASH is busy/ready
** ===================================================================
*/

byte ProgFlash_EraseFlash(byte Block);
/*
** ===================================================================
**     Method      :  ProgFlash_EraseFlash (component IntFLASH)
**
**     Description :
**         Erase all memory array of the selected Flash block.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Block           - Block number.
**                           Possible values:
**                            - PROG_FLASH_BLOCK
**                            - BOOT_FLASH_BLOCK
**     Returns     :
**         ---             - Error code, possible codes:
**                           - ERR_OK - OK
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available
**                           - ERR_RANGE - Block number is out of
**                           range
**                           - ERR_SPEED - This device does not work
**                           in the active speed mode
** ===================================================================
*/

byte ProgFlash_GetByteFlash(ProgFlash_TAddress Addr,byte *Data);
/*
** ===================================================================
**     Method      :  ProgFlash_GetByteFlash (component IntFLASH)
**
**     Description :
**         Get byte from address in FLASH.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to FLASH
**           Note: An address of the byte location is an 16-bit word
**                 location address multiplied by 2 and then the
**                 even/odd bytes are discriminated by LSB:
**                 0 for even byte, 1 for odd byte.
**       * Data            - Pointer to returned 8-bit data
**     Returns     :
**         ---             - Error code, possible codes:
**                           - ERR_OK - OK
**                           - ERR_RANGE - Address is out of range
** ===================================================================
*/

byte ProgFlash_SetGlobalProtection(bool ProtectAll);
/*
** ===================================================================
**     Method      :  ProgFlash_SetGlobalProtection (component IntFLASH)
**
**     Description :
**         Method makes all memory array of the selected FLASH
**         protected or unprotected. The protection state changes
**         are active till system reset.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ProtectAll      - TRUE - The whole flash
**                           memory array of the selected flash is
**                           protected; FALSE - The whole flash
**                           memory array of the selected flash is
**                           unprotected.
**     Returns     :
**         ---             - Error code, possible codes:
**                           - ERR_OK - OK
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available
**                           - ERR_VALUE - Read value is not equal to
**                           written value
**                           - ERR_SPEED - This device does not work
**                           in the active speed mode
** ===================================================================
*/

byte ProgFlash_SetBlockFlash(ProgFlash_TDataAddress Source,ProgFlash_TAddress Dest,word Count);
/*
** ===================================================================
**     Method      :  ProgFlash_SetBlockFlash (component IntFLASH)
**
**     Description :
**         Writes data to FLASH.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Source          - Source address of the data
**         Dest            - Destination address in FLASH
**         Count           - Count of the data fields in the
**                           smallest addressable units.
**           Note 1: The smallest addressable unit for the used CPU
**                   is byte.
**           Note 2: An address of a byte location is an 16-bit word
**                   location address multiplied by 2 and then the
**                   even/odd bytes are discriminated by LSB:
**                   0 for even byte, 1 for odd byte.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

#define ProgFlash_DataPtr2Addr(DataPtr) ((ProgFlash_TAddress)(DataPtr))
/*
** ===================================================================
**     Method      :  ProgFlash_DataPtr2Addr (component IntFLASH)
**
**     Description :
**         This method converts data pointer to format of a bean method
**         address parameter. Generally a data pointer format is
**         different from format of a method Addr parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Addr            - Data pointer.
**     Returns     :
**         ---             - Address in the format used in the bean
**                           methods.
**                           Version specific information for 56800
**                           derivatives ] 
**                           The return value is address of a byte
**                           location of the object the input parameter
**                           - pointer pointing at (address of a 16 bit
**                           word location multiplied by 2 and the least
**                           significant bit determines even or odd byte).
** ===================================================================
*/

#define ProgFlash_FuncPtr2Addr(FuncPtr) ((ProgFlash_TAddress)(FuncPtr))
/*
** ===================================================================
**     Method      :  ProgFlash_FuncPtr2Addr (component IntFLASH)
**
**     Description :
**         This method converts function pointer to format of a bean
**         method address parameter. Generally a function pointer
**         format is different from format of a method Addr parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Addr            - Function pointer.
**     Returns     :
**         ---             - Address in the format used in the bean
**                           methods.
**                           Version specific information for 56800
**                           derivatives ] 
**                           The return value is address of a byte
**                           location of the object the input parameter
**                           - pointer pointing at (address of a 16 bit
**                           word location multiplied by 2 and the least
**                           significant bit determines even or odd byte).
** ===================================================================
*/

/* END ProgFlash. */

#endif /* ifndef __ProgFlash */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
